Repository worldcoin/open-iris, pull requests merged in 2024-06, with the labels that each got.

#29 `open-iris` v1.1.0 documentation
  README.md
  colab/MatchingEntities.ipynb
  docs/source/_code_subpages/iris.nodes.normalization.rst
  docs/source/_code_subpages/iris.utils.rst
  docs/source/examples/custom_pipeline.rst
  docs/source/examples/matching_entities.rst
  docs/source/index.rst
  docs/source/issues_note.rst
  src/iris/io/dataclasses.py
  src/iris/nodes/geometry_refinement/contour_interpolation.py
  src/iris/nodes/iris_response/probe_schemas/regular_probe_schema.py
  src/iris/orchestration/output_builders.py
  src/iris/pipelines/iris_pipeline.py
  src/iris/utils/math.py
  tests/e2e_tests/orchestration/test_e2e_output_builder.py
  tests/unit_tests/pipelines/test_iris_pipeline.py
Labels: documentation

#31 A few minor adjustments after `open-iris` v1.1.0 release
  README.md
  colab/GettingStarted.ipynb
Labels: refactoring

#37 Bugfix: `geometry_mask` and `noise_mask` are always `None`.
  src/iris/orchestration/output_builders.py
Labels: bugfix
